#!/bin/bash
# THE ABLATION LADDER (2026-09-10). "If I knew then what I know now, what would I have built?" -- answered
# empirically, one component at a time, instead of by rebuilding the family from scratch.
#
# The recommendation is generated by:
#   ZERO_SEED=1 gen_variational.py "0,0,8,4" 0.3 0.08 out 0 "0,0,2,0" bidirectional-interpolation-propagated.glsl
# so its structural components can each be switched off at the generator, leaving everything else identical:
#
#   vp        the committed recommendation                            (the control)
#   noseed    ZERO_SEED=0     -- the zero seed, shipped 2026-09-06 on the owner's call
#   novar     iterations 0,0,0,0 -- the whole variational refinement cascade
#   noprop    built on the plain base instead of the propagated one -- flow propagation into flat regions
#   nomed     medians 0,0,0,0 -- measured 2026-09-09, included here so the table is complete
#
# Each is scored on the whole 42-case ladder and on three real sources including the cartoon. What this
# produces is the thing a from-scratch rebuild would have to discover anyway: which components earn their
# place TODAY, against the ladder as it stands now rather than as it stood when each was added.
# One GPU job at a time; unattended.
set -u
FFDIR="${FFDIR:-$HOME/np-build/ffmpeg}"   # the project ffmpeg build (BUILDANDUSAGE.md); mingw64/bin for its DLLs
export PATH="/c/msys64/mingw64/bin:$FFDIR:$PATH" FFMPEG="$FFDIR/ffmpeg.exe" FFPROBE="$FFDIR/ffprobe.exe"
SC="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"; NP="${NP_SCRATCH:-/e/nframe-project/np-scratch}"; G="$NP/ablate"
mkdir -p "$G"; cd "$SC/tests"
PROP=bidirectional-interpolation-propagated.glsl
echo "########## ABLATION start $(date +%T) at $(cd $SC && git rev-parse --short HEAD)"

gen() { ZERO_SEED=$1 python gen_variational.py "$2" 0.3 0.08 "$G/$4.glsl" 0 "$3" "$5" >/dev/null 2>&1 \
        && echo "  $4: $(grep -c '^//!HOOK' "$G/$4.glsl") passes" || echo "  $4: GENERATOR FAILED"; }
gen 1 "0,0,8,4" "0,0,2,0" vp     "$PROP"
gen 0 "0,0,8,4" "0,0,2,0" noseed "$PROP"
gen 1 "0,0,0,0" "0,0,2,0" novar  "$PROP"
gen 1 "0,0,8,4" "0,0,2,0" noprop bidirectional-interpolation.glsl
gen 1 "0,0,8,4" "0,0,0,0" nomed  "$PROP"
# the control must reproduce the committed file, or every delta below is measured against the wrong baseline
if cmp -s <(tail -n +12 "$G/vp.glsl") <(tail -n +12 "$SC/shaders/bidirectional-interpolation-variational-propagated.glsl"); then
  echo "  control reproduces the committed recommendation"
else
  echo "  CONTROL DIFFERS FROM THE COMMITTED FILE -- deltas would be meaningless; check the generator arguments"
fi

VARIANTS="vp noseed novar noprop nomed"
export OUTROOT="$G/ladder"; mkdir -p "$OUTROOT"
for v in $VARIANTS; do
  t0=$(date +%s)
  bash ./bench.sh all "$G/$v.glsl" "$v" < /dev/null 2>&1 | grep -iE "FAIL|error" | head -2 | sed "s/^/    [$v] /"
  echo "  ladder $v: $(( $(date +%s) - t0 )) s ($(date +%T))"
done
python ./analyze.py --variants 2>&1 | tee "$G/ladder-table.txt" | head -6

film() {
  local src="$1" tag="$2"; shift 2
  echo "  -- $tag [$*]"
  export OUTROOT="$G/real_$tag"; rm -rf "$OUTROOT"; mkdir -p "$OUTROOT"
  local v
  for v in $VARIANTS; do
    bash ./realbench.sh "$src" "$v" "$G/$v.glsl" "$@" < /dev/null 2>&1 | grep -iE "FAIL|ALARM" | head -2 | sed "s/^/    [$tag $v] /"
  done
  python ./realanalyze.py $VARIANTS 2>&1 | grep -E "^PSNR"
}
film "$NP/avengers.mp4"        avengers 600 3000 5400
film "$NP/backtothefuture.mkv" bttf     600 3000 5400
film "$NP/bluey.mkv"           bluey    60 180 300
echo "ABLATION DONE $(date +%T)"
