#!/usr/bin/env python3
"""Perturb every block-match cost by a few ULP, to expose tie-breaking fragility.

    ./tieprobe.py <src.glsl> <dst.glsl> <seed> [eps]

WHY THIS EXISTS. The block match picks an argmin over candidate offsets. Where
the cost surface is flat -- a near-tie -- an arithmetic difference far below any
meaningful cost difference can flip which candidate wins, and the whole warp for
that source pair is then built on the wrong vector. macOS shows this
catastrophically because its Vulkan/MoltenVK path is not bit-reproducible run to
run, so the perturbation arrives for free. Linux and Windows are bit-reproducible
and therefore hide it completely: re-running the benchmark there proves nothing,
because nothing perturbs the inputs.

This script supplies the perturbation deliberately, so the property can be
measured on a reproducible platform. It rewrites a shader so that every cost
compared by an argmin is nudged by a pseudo-random amount of relative size
`eps` (default 1e-6, i.e. a few float32 ULP -- far smaller than any real cost
difference, and comparable to what a different driver's summation order costs
you). The nudge is a hash of the cost's own bits and the candidate's identity,
so it is deterministic within a run and independent between candidates -- which
is precisely how genuine arithmetic divergence behaves.

Render two probed builds with different seeds and compare with framemd5. Every
frame that differs is a frame whose motion estimate was decided by noise rather
than by the image. See tieprobe.sh, which does exactly that.

framemd5, not PSNR: a PSNR figure rounded to two decimals hid a one-LSB
difference once already in this project and sent the analysis down the wrong
path for two commits.
"""
import pathlib
import re
import sys

if len(sys.argv) < 4:
    sys.exit(__doc__.strip().splitlines()[2].strip())

src, dst = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
seed = int(sys.argv[3]) & 0xFFFFFFFF
eps = float(sys.argv[4]) if len(sys.argv) > 4 else 1e-6

# A self-contained perturbation, with every constant baked in as a literal.
# It declares nothing at file scope and calls no helper, because in the
# mpv/libplacebo .hook format each //!HOOK block is its own compilation unit --
# a shared helper would have to be duplicated into all twelve of them.
#
# `ident` distinguishes candidates that score IDENTICALLY. Hashing the cost bits
# alone would give two exactly-tied candidates the same nudge and leave the tie
# unbroken, which is the one case most worth probing.
NUDGE = ("{{ uint h_ = floatBitsToUint({var}) ^ {seed}u ^ ({ident}); "
         "h_ ^= h_ >> 16; h_ *= 0x7feb352du; h_ ^= h_ >> 15; "
         "h_ *= 0x846ca68bu; h_ ^= h_ >> 16; "
         "{var} += (float(h_ & 0xffffu) * (1.0/32767.5) - 1.0) "
         "* {eps:.8g} * max(abs({var}), 1.0e-3); }}")


def nudge(var, ident, indent):
    return indent + NUDGE.format(var=var, ident=ident, seed=seed, eps=eps) + "\n"


text = src.read_text()
out, n_cand, n_incumbent = [], 0, 0

for line in text.splitlines(keepends=True):
    indent = line[:len(line) - len(line.lstrip())]

    # The incumbent's own cost is subject to the same arithmetic divergence as
    # every candidate's, so it gets perturbed too -- otherwise the probe would
    # understate the fragility by holding one side of every comparison fixed.
    # x/y are not in scope here, so the candidate identity is a constant.
    if re.match(r"\s*float best_cost = sad\d", line):
        out.append(line)
        out.append(nudge("best_cost", "0u", indent))
        n_incumbent += 1
        continue

    # Matches both the plain argmin and the TIE_MARGIN form that replaced it,
    # because the probe has to be runnable against the fixed shader -- that
    # comparison is the whole point of the measurement.
    m = re.match(r"(\s*)if \(cost < best_cost", line)
    if m:
        # Two argmin shapes exist. The eight block-match sites loop over
        # candidate offsets (x, y); the four vector-median sites loop over
        # candidate vectors (i). Bias the hash by whichever is in scope.
        before = "".join(out)
        blk = before[before.rfind("vec4 hook() {"):]
        if re.search(r"for \(int i = 0; i < 9; i\+\+\)", blk):
            ident = "uint(i) * 73856093u"
        else:
            ident = "uint(x + 16) * 73856093u + uint(y + 16) * 19349663u"
        out.append(nudge("cost", ident, m.group(1)))
        out.append(line)
        n_cand += 1
        continue

    out.append(line)

if n_cand == 0:
    sys.exit(f"no argmin sites found in {src} -- has the argmin been rewritten?")

banner = (f"// PROBED BUILD -- seed {seed}, eps {eps:g}. Generated by tests/tieprobe.py.\n"
          f"// Every argmin cost is nudged by a few ULP to expose tie-breaking\n"
          f"// fragility on a bit-reproducible platform. NOT for rendering video.\n")
dst.write_text(banner + "".join(out))
print(f"  {dst.name}: {n_cand} candidate sites, {n_incumbent} incumbent sites, "
      f"seed {seed}, eps {eps:g}")
